stages:
    - deploy

variables:
    APP_NAME: todo_app_backend

deploy:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    tags:
        - docker
    script:
        - unset DOCKER_HOST
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build . -t $CI_REGISTRY/ghostserver/$APP_NAME:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/ghostserver/$APP_NAME:$CI_PIPELINE_ID
        - echo "pushed image $APP_NAME:$CI_PIPELINE_ID"
        - docker logout $DOCKER_REGISTRY
    only:
        - master
