stages:
    - deploy

deploy:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    tags:
        - docker
    script:
        - docker build -t todo-app-backend .
        - docker stop backend || true && docker rm backend || true
        - docker run -d -p 3333:3333 --network danik_backend_network --ip 172.16.0.3 --restart=always --name backend todo-app-backend
        - echo "y" | docker system prune
    only:
        - master
